name: Style2js CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
            node-version: '14.x'
      - name: Install dependencies
        run: npm install 
      - name: Test
        run: npm run test 
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
